# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5ed0485f791f85fdec9f01a21afcdffe3d3d002053d4a64deaa405a7a0feffbaa34628484d9e3d1065246e486a4d55245dc4711a0ceb9007ec0f8381a626b0a

test:
  secret_key_base: 7d18c62986d3fae4181723fa123f50fd4f13a350e732de6d3977c7f3ff84b01e8603173117b9eb139d574824aab8a62939a6214565e33ae97e893bb2fe313053

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
